name: Merge Conflict Labeler

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  label:
    name: Labeling
    runs-on:
      size: 2x8
      image: g7r5wqb57k.registry.depot.dev/ci:latest
    if: ${{ github.repository == 'getarcaneapp/arcane' && (github.event_name == 'push' || github.event.workflow_run.event == 'pull_request') }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Request App Token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.ARCANE_APP_CLIENT_ID }}
          private-key: ${{ secrets.ARCANE_APP_PRIVATE_KEY }}
          owner: getarcaneapp
          repositories: arcane
          permission-pull-requests: write

      - name: Apply label
        uses: eps1lon/actions-label-merge-conflict@0273be72a0bbd58fcd71d0d6c02c209b50d1e5e1 # v3.1.0
        with:
          dirtyLabel: "merge conflict"
          commentOnDirty: "This pull request has merge conflicts. Please resolve the conflicts so the PR can stay up-to-date and reviewed."
          repoToken: "${{ steps.app-token.outputs.token }}"
