name: Potential Duplicate Issues
on:
    issues:
        types: [opened, edited]

jobs:
    run:
        runs-on: linux
        steps:
            - name: Request App Token
              id: app-token
              uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
              with:
                  client-id: ${{ secrets.ARCANE_APP_CLIENT_ID }}
                  private-key: ${{ secrets.ARCANE_APP_PRIVATE_KEY }}
                  owner: getarcaneapp
                  repositories: arcane
                  permission-issues: write

            - uses: wow-actions/potential-duplicates@4d4ea0352e0383859279938e255179dd1dbb67b5 # v1.1.0
              with:
                  GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
                  filter: ""
                  exclude: "regression"
                  label: potential-duplicate
                  state: all
                  threshold: 0.6
                  reactions: "confused"
                  comment: |
                      We have found issues that are potential duplicates: {{#issues}}
                        - #{{ number }} ({{ accuracy }}%)
                      {{/issues}}

                      If any of the issues listed above are a duplicate, please consider closing this issue & upvoting/commenting the original one.
                      Doing so will help prioritize bugs and features.
